#!/bin/bash

set ${CHANG_SET:--eu}

for source in ${BASH_SOURCE%/*}/sources/*.sh; do
  f=$source
  f=${f##*/}
  f=${f%%.sh}

    source $source
done

CHANG_SYNC_IMAGE="majkel/chang-sync"
CHANG_SYNC_SERVER_PORT=5000
CHANG_UID=${CHANG_UID:-1000}
CHANG_GID=${CHANG_GID:-1000}
CHANG_PWD="${CHANG_PWD:-$(pwd -P)}"
APP_PATH="${CHANG_PWD}"
CHANG_APP_NAME=${CHANG_PWD##*/}
CHANG_MIN_IMAGE=${CHANG_MIN_IMAGE:-$CHANG_SYNC_IMAGE}

sync() {
  local verbose=${1:-false}
  trap chang_sync_stop EXIT
  chang_sync_start_client $(${verbose} || echo -silent) -repeat watch -prefer ${APP_PATH} -killserver -perms -1
}

sync_daemon() {
  sync | read _fail_fast & disown
}

case "${@:-}" in
  ""|start)
    chang_sync_start
    echo $(chang_sync_volume)
    ;;
  stop)
    chang_sync_stop
    ;;
  verbose)
    chang_sync_start_verbose
    ;;
  restart)
    chang_sync_stop
    chang_sync_start
    ;;
  *)
    chang_error "Usage: chang-sync [start|stop|restart|verbose]"
    ;;
esac
